spring.application.name=backend
server.port=8080

# Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/erp_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- CẤU HÌNH JWT (Token xác thực) ---
# Chuỗi bí mật dùng để ký token
erp.app.jwtSecret=mySuperSecretKeyForERPWarehouseManagementSystemProject2026SecureKey
# Thời gian token hết hạn (86400000 ms = 24 giờ)
erp.app.jwtExpirationMs=86400000
